### ISSUE TITLE
Add an AppIcon

### ISSUE THREAD

**Issue by bircni** [simone-di-paolo/randomteamsgenerator#17]
Maybe also add an AppIcon - if you need help feel free to ask 😄

**Comment by simone-di-paolo** [comment]
Thank you again, @bircni ! 😄 Sure!
Do you have any advice for the app icon?

**Comment by bircni** [comment]
What do you think about this one?

![randomteamsgenerator_icon](https://user-images.githubusercontent.com/75789103/217057140-9701eb2a-086e-4aa5-b414-0bf4694febf8.png)

**Comment by simone-di-paolo** [comment]
I was thinking about something about "Teams shirt" and the random symbol. 
What you think?

I can try to figure it out something on Figma!

**Comment by bircni** [comment]
What do you mean?

**Comment by simone-di-paolo** [comment]
App icon created!
Thanks bircni! 😄
